<?php

namespace App\Providers;

use App\Service\CutiService;
use App\Service\Impl\CutiServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class CutiServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(CutiService::class,CutiServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [CutiService::class]; // TODO: Change the autogenerated stub
    }
}
