<?php

namespace App\Providers;

use App\Service\DepartemenService;
use App\Service\Impl\DepartemenServiceImpl;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class DepartemenServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(DepartemenService::class,DepartemenServiceImpl::class);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [DepartemenService::class]; // TODO: Change the autogenerated stub
    }
}
