<?php

namespace App\Providers;

use App\Service\Impl\JabatanServiceImpl;
use App\Service\JabatanService;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class JabatanServiceProvider extends ServiceProvider implements DeferrableProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(JabatanService::class,JabatanServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [JabatanService::class]; // TODO: Change the autogenerated stub
    }
}
