<?php

namespace App\Providers;

use App\Service\Impl\JenisCutiServiceImpl;
use App\Service\JenisCutiService;
use Illuminate\Support\ServiceProvider;

class JenisCutiServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->singleton(JenisCutiService::class,JenisCutiServiceImpl::class);

    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }

    public function provides()
    {
        return [JenisCutiService::class]; // TODO: Change the autogenerated stub
    }
}
